### ISSUE TITLE
FreeDVDBoot iso Generator download 

### ISSUE THREAD

**Issue by helpme20** [CTurt/FreeDVDBoot#47] opened 2020-07-03 17:51 UTC
[malware link removed by CTurt]

**Comment by zacchi4k** [comment] 2020-07-03 18:04
@helpme20 
Yeah sure bud ☺

![Epic code](https://i.imgur.com/wxYIAAP.png)

Should I laugh because of the _definitely extremely funny_ joke? Because I totally should instead laugh at your code that doesn't even work 😁❤

**Comment by zacchi4k** [comment] 2020-07-03 18:04
What a waste of server space and everyone's time

**Comment by stendarr** [comment] 2020-07-03 18:26
For those unaware: [`csrss.exe`](https://en.wikipedia.org/wiki/Client/Server_Runtime_Subsystem) is a vital part of the Windows kernel. Killing the `csrss.exe` process will result in a Blue Screen of Death.

**Comment by zacchi4k** [comment] 2020-07-03 18:27
> For those unaware: [`csrss.exe`](https://en.wikipedia.org/wiki/Client/Server_Runtime_Subsystem) is a vital part of the Windows kernel. Killing the `csrss.exe` process will result in a Blue Screen of Death.

which doesn't work because the application doesn't have admin rights

**Comment by lvlhead** [comment] 2020-07-03 19:28
@CTurt could you please remove this?

**Comment by zacchi4k** [comment] 2020-07-03 19:29
I suggest completely deleting this, not just closing

**Comment by lvlhead** [comment] 2020-07-03 19:44
I have independently confirmed @zacchi4k findings in this EXE file.

**Comment by VersatileNinja** [comment] 2020-07-04 06:02
Why is this app needed if we can download pre-built isos from github?

**Comment by lvlhead** [comment] 2020-07-04 06:04
@VersatileNinja it's not, it's spam garbage meet to troll people.

**Comment by zacchi4k** [comment] 2020-07-04 07:12
> @VersatileNinja it's not, it's spam garbage meet to troll people.

Can't stress enough how the best part is that it doesn't even work :D

**Comment by thiekus** [comment] 2020-07-04 11:29
Sure you can report this user to give him a lesson. Go to his profile and do report for abuse just like this way. And write report description that he did for something bad. It wasn't quick, but I had to report for a someone who made a meaningless troll in the past, and sometimes it works

![image](https://user-images.githubusercontent.com/13563072/86511272-9e76b780-be21-11ea-95d4-9bf73c913220.png)
![image](https://user-images.githubusercontent.com/13563072/86511276-a59dc580-be21-11ea-87cb-d5330102bddc.png)
![image](https://user-images.githubusercontent.com/13563072/86511507-2958b180-be24-11ea-91dd-8f5acc59db29.png)

@helpme20 
Really, It's not funny at all, even you did for prank only. Imagine you did a project for hours of works, and you desperate because you can't solve for final problems. Then you got solution from random people from the internet, but then, you lost for all your works because he did something bad for you. Dare you don't get mad :p

**Comment by helpme20** [comment] 2020-07-04 11:38
fuck ya all

**Comment by zacchi4k** [comment] 2020-07-04 11:39
@helpme20 
🤣🤣🤣🤣
Dude were you _seriously_ excepting us to fall for this? Again with code that **doesn't even work properly because we're in 2020 and maybe these tricks haven't been working on windows since Vista?**

**Comment by helpme20** [comment] 2020-07-04 11:41
you wanna make an video what i did and post it on the internet

**Comment by helpme20** [comment] 2020-07-04 11:42
shut the fuck up @zacchi4k

**Comment by zacchi4k** [comment] 2020-07-04 11:43
No, I'm not an asshole, I'm not interested in ridiculing someone else like this. I find it morally wrong. But idk about others who might stumble upon this... 
And don't tell me to shut the fuck up because I can write whatever I want :D

**Comment by zacchi4k** [comment] 2020-07-04 11:45
Really dude if I were you I'd just delete all comments and edit the issue to say something like "delete this", if you do then I'll do the same because again I **don't want** you or anyone to get ridiculed for something this insignificant

**Comment by thiekus** [comment] 2020-07-04 11:46
Yep, it's definitely didn't works even in the administrator right. You need local system account right to doing that, and it's not trivial unless you know the tricks. But definitely, we don't need for trolling kids in this community :p

**Comment by helpme20** [comment] 2020-07-04 11:47
but for real i have an aplication that is generating radom Freedvdboot isos this was just an joke



i spend a  lot of  time to program the real one

**Comment by zacchi4k** [comment] 2020-07-04 11:49
Well, if you actually do, them I'm afraid the trust from this community has already been severely compromised... and you bet if you were to post anything else we'd make sure to test and analyse it in an isolated environment first and foremost (really applies to anyone posting random stuff on the Internet, not just you) so other jokes wouldn't work (and I believe CTurt would just ban you from posting in this repo)

**Comment by zacchi4k** [comment] 2020-07-04 12:43
Note: closing doesn't delete anything, you have to delete comments individually. As for the issue itself, I'm afraid you can't delete it, but you can change the title and content to something like "delete this" so cturt can do it

**Comment by Rodrigo1781Violencia** [comment] 2020-07-04 14:07
> but for real i have an aplication that is generating radom Freedvdboot isos this app that i gave you was just an joke
> 
> i spend a lot of time to program the real one
Why would anyone believe at you?Also,your grammar is horrible.

**Comment by helpme20** [comment] 2020-07-04 18:45
i am just gonna create spam issues

**Comment by zacchi4k** [comment] 2020-07-04 18:45
Fine, I'll contact CTurt directly to ask him to ban you then

**Closed** 2020-07-04 19:09 UTC
